version: '3'

######### Services ###################################

services:
  # Server container
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 3306:80
  nginx:
    build:
      context: docker/dev/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/dev/nginx/logs:/var/log/nginx
    ports:
      # Nuxt port
      - 8080:80
      # Laravel port
      - 8888:81
    links:
      - node
      - php

  # PHP FastCGI Process Manager container
  php:
    build:
      context: docker/dev/php
      dockerfile: Dockerfile
    volumes:
      - ./quiz-g-back:/var/www/quiz-g-back
    environment:
      # If you down want to use xDebug, set remote_enable=0
      XDEBUG_CONFIG: "remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"

  # Node container
  node:
    build:
      context: docker/dev/node
      dockerfile: Dockerfile
    volumes:
      - ./quiz-g-front:/var/www/quiz-g-front
  # MySQL container


######### Volumes ###################################

volumes:
  database:
    driver: local
  redis:
    driver: local